22 - Custom colors
sirius-ea/VireoXlibrary pull request #39
Opened 2024-01-05 12:53 UTC by Phoenonical

The variant `Default` on some components now use a globally defined theme (E.g. VrxButton).
A new story was added in Storybook called "VrxColorPalette".

The theme is the following: 

```js
colors: {
      primary: {
          ...colors.gray
      },
      secondary: {
        ...colors.blue
      },
      neutral: {
          ...colors.gray,
      },
      error: {
        ...colors.red
      },
      base: {
          "content-light": colors.slate['950'],
          "content-dark":  colors.slate['50'],
          light: colors.gray['100'],
          dark: colors.gray['700']
      },
      'icon': colors.gray['400'],
      'icon-disabled': colors.gray['300'],
      'icon-invalid': colors.red['600'],
},
```

2024-01-08 15:06 UTC, Crish15 commented
Ho un po' guardato la PR e ho dei dubbi sui colori utilizzati nei componenti: dove prima c'era il colore grigio ora c'è il colore primary... Questo è pericoloso e potrebbe distruggere lo stile di tutti i componenti. Direi di snellire questa PR e cancellare tutte le modifiche allo style dei componenti, scorporandole poi in pr più piccole. In questo modo possiamo analizzare lo stile di ogni singolo componente

2024-01-08 15:06 UTC, Crish15 commented on tailwind.config.js
> +        neutral: {
i colori vanno da 50 a 950, 0 e 1000 non sono accettati

2024-01-08 15:41 UTC, Phoenonical commented on tailwind.config.js
> +        neutral: {
Quelli due valori esistono principalmente per il text, che non avevo un'idea chiara come definirli. 
Sarebbe meglio definire 'text-dark'/'text-light' come colori? Oppure non vogliamo permettere ai utenti di modificare il colore del testo?

2024-01-08 16:36 UTC, Crish15 commented
> > Ho un po' guardato la PR e ho dei dubbi sui colori utilizzati nei componenti: dove prima c'era il colore grigio ora c'è il colore primary... Questo è pericoloso e potrebbe distruggere lo stile di tutti i componenti. Direi di snellire questa PR e cancellare tutte le modifiche allo style dei componenti, scorporandole poi in pr più piccole. In questo modo possiamo analizzare lo stile di ogni singolo componente
> 
> Principalmente primary è il colore grigio. Ho sostituito i keyword 'gray' con 'primary' (Senza toccare il valore dopo il trattino `-`). Poi ho copiato i valori del colore Gray su Primary. Però facendo così ho principalmente modificato solo il default colore del VrxButton, e leggermente modificato i colori di VrxGrid (Dove c'era lo sfondo bianco, è stato sostituito con bg-primary-50). Oltre a quelli due modifiche, confrontando il mio PR con la tema originale, mi sembrano identici.
> 
> Però per facilitare l'analisi, non è un problema a fare tanti PR piccoline per ogni componente + uno per definire i colori nel tailwind,config.js.
> 
> **EDIT**
> 
> La stessa logica è stato applicato per il colore blu nei component. E' stato definito come 'Secondary'

Allora per quanto riguarda i componenti guardiamo assieme tutte le modifiche e le commentiamo in "Live". Considera che Primary per me è un colore di accento, mentre il grigio lo vedo come un colore solitamente di sfondo. Bisogna provare a prendere una palette di qualche prodotto famoso (vedi i principali social) e applica il colore primary, per capire come renderebbe nel caso di utilizzo reale.

Per quanto riguarda invece i valori 0 e 1000 preferisco di gran lunga (e penso sia anche più comprensibile) text-light e text-dark, permettono anche più "personalizzazione".

2024-01-10 14:48 UTC, Crish15 requested changes

2024-01-10 14:48 UTC, Crish15 commented on src/components/VrxDatePicker/VrxDatePicker.vue
> +      class="relative text-text-lightMode dark:text-text-darkMode"
c'è un text di troppo (qui e anche nelle altre parti in giro per il codice)

2024-01-10 14:48 UTC, Crish15 commented on src/components/VrxDatePicker/pickers/DaysPick.vue
> +        class="rounded-lg font-bold hover:bg-primary-200 dark:hover:bg-primary-500 pt-1 pb-1 pr-2 pl-2 cursor-pointer select-none hover:text-secondary-700 dark:hover:text-neutral-0"
ci sono ancora dei neutral-0 da rimuovere e sostituire

2024-01-10 14:48 UTC, Crish15 commented on tailwind.config.js
> +        'text-lightMode': colors.slate['950'],
toglierei "MODE" dal nome di queste impostazioni

2024-01-10 14:48 UTC, Crish15 commented on tailwind.config.js
> +        'background-lightMode': colors.gray['100'],
ho visto che hai definito background-light e background dark, ma in giro per i componenti utilizzi bg-neutral-50. Usa queste due classi che hai definito.

fai diventare background --> bg

2024-01-16 09:10 UTC, Crish15 commented on src/components/VrxDateRangePicker/VrxDateRangePicker.css
> +        @apply text-text-lightMode/80;
text-text ripetuto

2024-01-16 09:11 UTC, Crish15 commented on src/components/VrxDateRangePicker/VrxDateRangePicker.css
> +        @apply dark:text-text-darkMode/80;
text-text ripetuto

2024-01-16 09:11 UTC, Crish15 commented on src/components/VrxDateRangePicker/VrxDateRangePicker.css
> +        @apply bg-bg-lightMode;
bg-bg ripetuto

2024-01-16 09:12 UTC, Crish15 commented on src/components/VrxGrid/VrxGrid.css
> +        @apply bg-bg-lightMode;
bg-bg ripetuto

2024-01-16 09:12 UTC, Crish15 commented on src/components/VrxGrid/VrxGrid.css
> +        @apply dark:bg-bg-darkMode;
bg-bg ripetuto

2024-01-16 09:13 UTC, Crish15 commented on src/components/VrxInput/VrxInput.css
> +        @apply dark:text-text-darkMode dark:bg-bg-darkMode dark:border-primary-600 dark:placeholder-text-darkMode/30 dark:focus:ring-secondary-500 dark:focus:border-secondary-500;
text-text ripetuto e bg-bg ripetuto

2024-01-16 09:13 UTC, Crish15 commented on src/components/VrxInput/VrxInput.css
> +        @apply bg-bg-lightMode/90 text-text-lightMode/60;
bg-bg e text-text

2024-01-16 09:31 UTC, Crish15 commented on src/components/VrxButton/VrxButton.css
> +        @apply text-text-dark;
text-text

2024-01-16 09:31 UTC, Crish15 commented on src/components/VrxNavbar/VrxNavbar.css
> +        @apply dark:text-text-dark md:dark:text-secondary-500;
text-text

2024-01-16 09:32 UTC, Crish15 commented on src/components/VrxNavbar/VrxNavbar.css
> +        @apply text-text-dark bg-secondary-700;
text-text

2024-01-16 09:32 UTC, Crish15 commented on src/components/VrxNavbar/VrxNavbar.css
> +        @apply dark:text-text-dark md:dark:hover:text-secondary-500 dark:hover:bg-primary-700 dark:hover:text-text-dark md:dark:hover:bg-transparent;
text-text

2024-01-16 09:32 UTC, Crish15 commented on src/components/VrxNavbar/VrxNavbar.css
> +        @apply text-text-light md:hover:text-text-light/80;
text-text

2024-01-16 09:32 UTC, Crish15 commented on src/components/VrxNavbar/VrxNavbar.css
> +        @apply dark:text-text-dark md:dark:hover:text-text-dark/80;
text-text

2024-01-16 13:56 UTC, Crish15 approved these changes

2024-01-16 13:57 UTC, merged