Added VrxNotification component
sirius-ea/VireoXlibrary pull request #63
Opened 2024-11-21 11:05 UTC by fed301

2024-11-26 08:33 UTC, gfrancesca approved these changes

2024-11-26 09:19 UTC, Phoenonical submitted a review, later dismissed

2024-11-26 09:39 UTC, gfrancesca commented
Bisognerebbe aggiungere un po' di documentazione in più su come utilizzare le notifiche, in particolare spiegare meglio i parametri (tipo duration, se impostato a 0, la notifica resta per sempre e bisogna cliccare sulla notifica per rimuoverla)

2024-11-26 09:40 UTC, gfrancesca requested changes
risolvere gli ultimi commenti lasciati

2024-11-27 08:22 UTC, Phoenonical approved these changes

2024-12-09 12:10 UTC, gfrancesca approved these changes

2024-12-09 12:10 UTC, merged